AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    zoneName:
        Type: String
Resources:
    DNS:
        Type: "AWS::Route53::HostedZone"
        Properties:
            HostedZoneConfig:
                Comment: "Hosted zone for records related to EKS services"
            Name: !Ref zoneName
            HostedZoneTags:
                -
                  Key: "Name"
                  Value: !Ref zoneName
Outputs:
    hostedZoneId:
        Description: 'id of eks hosted zone'
        Value: !Ref DNS
        Export:
            Name: !Sub '${AWS::StackName}-hostedZoneId'
